import type { Metadata } from "next";
import "./globals.css";



import { Figtree } from "next/font/google";

const jessey = Figtree({
  subsets: ["latin-ext"], // ระบุ subset ที่ต้องการใช้ เช่น latin, latin-ext
  weight: ["300","400","500","600"], // น้ำหนักของฟอนต์
  style: "normal", // สไตล์ของฟอนต์ (normal หรือ italic)
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jessey.className} antialiased`}>
        <div className="bg-black min-h-screen flex flex-col">
          <div className="bg-[#D6D6D6] flex justify-center font-light text-black text-xl sm:text-2xl lg:text-4xl text-center items-center py-4 md:h-[15vh] h-[10vh]">
            Smart Door Bell
          </div>
          <div className="flex-grow">{children}</div>
        </div>
      </body>
    </html>
  );
}

